# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_v3.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coins(object):
    def setupUi(self, coins):
        coins.setStyleSheet("background-color: black;")
        coins.setObjectName("coins")
        coins.resize(1277, 736)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(95, 127, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 127, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 127, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        coins.setPalette(palette)
        coins.setTabletTracking(False)
        coins.setLayoutDirection(QtCore.Qt.LeftToRight)
        coins.setAutoFillBackground(False)
        self.list_1 = QtWidgets.QListView(coins)
        self.list_1.setGeometry(QtCore.QRect(50, 150, 171, 271))
        self.list_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_1.setObjectName("list_1")
        self.list_1.setStyleSheet('color: #f3ba2f')
        self.list_1.setStyleSheet('background-color:#f3ba2f')
        self.button_1 = QtWidgets.QPushButton(coins)
        self.button_1.setGeometry(QtCore.QRect(80, 430, 113, 32))
        self.button_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_1.setObjectName("button_1")
        self.button_1.setStyleSheet('color: #f3ba2f')
        self.button_1.setStyleSheet('background-color:#f3ba2f')
        self.list_2 = QtWidgets.QListView(coins)
        self.list_2.setGeometry(QtCore.QRect(390, 150, 151, 271))
        self.list_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_2.setObjectName("list_2")
        self.list_2.setStyleSheet('color: #f3ba2f')
        self.list_2.setStyleSheet('background-color:#f3ba2f')
        self.buttonBox = QtWidgets.QDialogButtonBox(coins)
        self.buttonBox.setGeometry(QtCore.QRect(1020, 590, 164, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setStyleSheet('color: #f3ba2f')
        self.buttonBox.setStyleSheet('background-color:#f3ba2f')
        self.button_2 = QtWidgets.QPushButton(coins)
        self.button_2.setGeometry(QtCore.QRect(410, 430, 113, 32))
        self.button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_2.setObjectName("button_2")
        self.button_2.setStyleSheet('color: #f3ba2f')
        self.button_2.setStyleSheet('background-color:#f3ba2f')
        self.list_3 = QtWidgets.QListView(coins)
        self.list_3.setGeometry(QtCore.QRect(710, 150, 151, 271))
        self.list_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_3.setStyleSheet('background-color:#f3ba2f')
        self.list_3.setObjectName("list_3")
        self.list_3.setStyleSheet('color: #f3ba2f')
        self.list_3.setStyleSheet('background-color:#f3ba2f')
        self.button_3 = QtWidgets.QPushButton(coins)
        self.button_3.setGeometry(QtCore.QRect(720, 430, 113, 32))
        self.button_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_3.setObjectName("button_3")
        self.button_3.setStyleSheet('color: #f3ba2f')
        self.button_3.setStyleSheet('background-color:#f3ba2f')
        self.list_4 = QtWidgets.QListView(coins)
        self.list_4.setGeometry(QtCore.QRect(870, 150, 151, 271))
        self.list_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_4.setObjectName("list_4")
        self.list_4.setStyleSheet('color: white')
        self.list_4.setStyleSheet('background-color:#f3ba2f')
        self.list_4.setStyleSheet('background-color:#f3ba2f')
        self.button_4 = QtWidgets.QPushButton(coins)
        self.button_4.setGeometry(QtCore.QRect(890, 430, 113, 32))
        self.button_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_4.setObjectName("button_4")
        self.button_4.setStyleSheet('color: #f3ba2f')
        self.button_4.setStyleSheet('background-color:#f3ba2f')
        self.list_5 = QtWidgets.QListView(coins)
        self.list_5.setGeometry(QtCore.QRect(1030, 150, 151, 271))
        self.list_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_5.setObjectName("list_5")
        self.list_5.setStyleSheet('color: #f3ba2f')
        self.list_5.setStyleSheet('background-color:#f3ba2f')
        self.button_5 = QtWidgets.QPushButton(coins)
        self.button_5.setGeometry(QtCore.QRect(1050, 430, 113, 32))
        self.button_5.setStyleSheet('background-color:#f3ba2f')
        self.button_5.setStyleSheet('background-color:#f3ba2f')
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(158, 255, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 193, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 255, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 193, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 255, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 193, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.button_5.setPalette(palette)
        self.button_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_5.setObjectName("button_5")
        self.button_5.setStyleSheet('color: #f3ba2f')
        self.button_5.setStyleSheet('background-color:#f3ba2f')
        self.label = QtWidgets.QLabel(coins)
        self.label.setGeometry(QtCore.QRect(100, 120, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setStyleSheet('color: #f3ba2f')
        self.label_2 = QtWidgets.QLabel(coins)
        self.label_2.setGeometry(QtCore.QRect(440, 120, 70, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet('color: #f3ba2f')
        self.label_3 = QtWidgets.QLabel(coins)
        self.label_3.setGeometry(QtCore.QRect(750, 120, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet('color: #f3ba2f')
        self.label_4 = QtWidgets.QLabel(coins)
        self.label_4.setGeometry(QtCore.QRect(900, 120, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet('color: #f3ba2f')
        self.label_5 = QtWidgets.QLabel(coins)
        self.label_5.setGeometry(QtCore.QRect(1050, 120, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet('color: #f3ba2f')
        self.label_6 = QtWidgets.QLabel(coins)
        self.label_6.setGeometry(QtCore.QRect(270, 120, 70, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_6.setStyleSheet('color: #f3ba2f')
        self.button_6 = QtWidgets.QPushButton(coins)
        self.button_6.setGeometry(QtCore.QRect(240, 430, 113, 32))
        self.button_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_6.setObjectName("button_6")
        self.button_6.setStyleSheet('color: #f3ba2f')
        self.button_6.setStyleSheet('background-color:#f3ba2f')
        self.list_6 = QtWidgets.QListView(coins)
        self.list_6.setGeometry(QtCore.QRect(230, 150, 151, 271))
        self.list_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_6.setObjectName("list_6")
        self.list_6.setStyleSheet('color: #f3ba2f')
        self.list_6.setStyleSheet('background-color:#f3ba2f')
        self.label_7 = QtWidgets.QLabel(coins)
        self.label_7.setGeometry(QtCore.QRect(600, 120, 100, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_7.setStyleSheet('color: #f3ba2f')
        self.button_7 = QtWidgets.QPushButton(coins)
        self.button_7.setGeometry(QtCore.QRect(570, 430, 113, 32))
        self.button_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_7.setObjectName("button_7")
        self.button_7.setStyleSheet('color: #f3ba2f')
        self.button_7.setStyleSheet('background-color:#f3ba2f')
        self.list_7 = QtWidgets.QListView(coins)
        self.list_7.setGeometry(QtCore.QRect(550, 150, 151, 271))
        self.list_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_7.setObjectName("list_7")
        self.list_7.setStyleSheet('color: #f3ba2f')
        self.list_7.setStyleSheet('background-color:#f3ba2f')
        self.label_8 = QtWidgets.QLabel(coins)
        self.label_8.setGeometry(QtCore.QRect(60, 500, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.label_8.setStyleSheet('color: #f3ba2f')
        self.label_9 = QtWidgets.QLabel(coins)
        self.label_9.setGeometry(QtCore.QRect(60, 530, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.label_9.setStyleSheet('color: #f3ba2f')
        self.lineEdit = QtWidgets.QLineEdit(coins)
        self.lineEdit.setGeometry(QtCore.QRect(210, 500, 131, 21))
        self.lineEdit.setStyleSheet('color: White')
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(coins)
        self.doubleSpinBox.setGeometry(QtCore.QRect(210, 530, 131, 22))
        self.doubleSpinBox.setStyleSheet('color: White')
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_10 = QtWidgets.QLabel(coins)
        self.label_10.setGeometry(QtCore.QRect(50, 40, 141, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Ekran Resmi 2021-05-02 16.23.21.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_10.setStyleSheet('color: #f3ba2f')

        self.retranslateUi(coins)
        QtCore.QMetaObject.connectSlotsByName(coins)
    def retranslateUi(self, coins):
        _translate = QtCore.QCoreApplication.translate
        coins.setWindowTitle(_translate("coins", "Binance Coin Arayüzü"))
        self.button_1.setText(_translate("coins", "COİN"))
        self.button_2.setText(_translate("coins", "FİYAT AL"))
        self.button_3.setText(_translate("coins", "MİKTAR"))
        self.button_4.setText(_translate("coins", "DÜŞÜK"))
        self.button_5.setText(_translate("coins", "YÜKSEK"))
        self.label.setText(_translate("coins", "Coin İsim"))
        self.label_2.setText(_translate("coins", "Fiyat(TRY)"))
        self.label_3.setText(_translate("coins", "Miktar"))
        self.label_4.setText(_translate("coins", "En Düşük Tutar"))
        self.label_5.setText(_translate("coins", "En Yüksek Tutar"))
        self.label_6.setText(_translate("coins", "Favoriler"))
        self.button_6.setText(_translate("coins", "FAVORİ"))
        self.label_7.setText(_translate("coins", "Fiyat(BUSD)"))
        self.button_7.setText(_translate("coins", "FİYAT AL"))
        self.label_8.setText(_translate("coins", "Alınacak Tutar:"))
        self.label_9.setText(_translate("coins", "Alınacak Miktar:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    coins = QtWidgets.QWidget()
    ui = Ui_coins()
    ui.setupUi(coins)
    coins.show()
    sys.exit(app.exec_())
